[server]
headless = false
port = 8501
enableCORS = true
enableWebsocketReconnects = true
enableCORSForLocalhost = false

[theme]
primaryColor = "#FFCC00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"

